export { default as footerStyles } from './components/footer.styles'
export { default as layoutStyles } from './components/layout.styles'
export { default as navStyles } from './components/nav.styles'
export { default as notFoundStyles } from './components/404.styles'
export { default as homeStyles } from './components/sections/home.styles'
export { default as aboutStyles } from './components/sections/about.styles'
export { default as skillStyles } from './components/sections/skills.styles'
export { default as expStyles } from './components/sections/exp.styles'